name: Python build

on:
    push:
        branches:
            - master
    pull_request:
        branches: [master]

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
                  architecture: x64
            - name: Install dependencies
              run: pip install -r requirements/common.txt -r requirements/dev.txt
            - name: Format and lint
              run: chmod +x check_format_lint.sh && ./check_format_lint.sh

    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: [3.6, 3.7, 3.8]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
                  architecture: x64
            - name: Install dependencies
              run: pip install -r requirements/common.txt -r requirements/dev.txt
            - name: Python test
              run: pytest

    tests-pypy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: pypy3
                  architecture: x64
            - name: Install dependencies
              run: pip install -r requirements/common.txt pytest
            - name: Python test
              run: pytest
